version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: psplay_postgres
    environment:
      POSTGRES_DB: psplay_db
      POSTGRES_USER: psplay_user
      POSTGRES_PASSWORD: psplay_password
    ports:
      - "5432:5432"
    volumes:
      - psplay_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  psplay_postgres_data: