version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: psplay_postgres
    restart: always
    environment:
      POSTGRES_DB: psplay_db
      POSTGRES_USER: psplay_user
      POSTGRES_PASSWORD: psplay_password123
    ports:
      - "5433:5432"
    volumes:
      - psplay_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psplay_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: psplay_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://psplay_user:psplay_password123@postgres:5432/psplay_db
      - JWT_SECRET=2b7e151628aed2a6abf7158809cf4f3c
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: psplay_frontend
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    command: npm run dev

volumes:
  psplay_postgres_data:
